# Your project's server will run on localhost:xxxx at this port
DEVURL: 'http://localhost/okon'

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "assets/**/*"
    - "!assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules"
  # Paths to JavaScript libraries, which are combined into one file
  # TODO:  Rework this using webpack build. Right now just verifying the files are being built properly
  entries:
    - "assets/js/app.js"
